### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by OrnicarLichess** [DakshCodess/DinoGame#7]
Please remove the heading show in the game 
![Screenshot_2022-02-25-00-03-23-268](https://user-images.githubusercontent.com/100345597/155585942-f734e61a-2c85-4354-b2f4-9ba7b214e941.jpeg)

**Comment by DakshCodess** [comment]
Fixed , thx for raising issue . By the way it is not a big anymore . Its just an opening title .
